name: PHPUnit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ci4_test
          MYSQL_USER: ci4
          MYSQL_PASSWORD: secret
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # PHP 8.4 not officially released; use stable
          extensions: mbstring, intl, bcmath, pdo, mysqli, xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Wait for MySQL
        run: sleep 15

      - name: Create test database structure
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u ci4 -psecret ci4_test < tests/_support/your_test_db.sql

      - name: Run PHPUnit tests
        env:
          database.tests.hostname: 127.0.0.1
          database.tests.database: ci4_test
          database.tests.username: ci4
          database.tests.password: secret
          database.tests.DBDriver: MySQLi
          database.tests.DBPrefix: ''
        run: ./vendor/bin/phpunit --coverage-text
