name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: atelier1
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, bcmath, pdo_mysql
          coverage: xdebug

      - name: Set up environment variables
        run: cp .env.github .env

      - name: Show .env file content (debug)
        run: cat .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Execute schema.sql to create tables
        run: |
          mysql -h127.0.0.1 -utest_user -ptest_password atelier1 < schema.sql

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --colors=always --coverage-text
