name: Run PHPUnit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: |
        composer install
        composer require kint-php/kint:"^4.1"   # This will install the right Kint version
        composer update

    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --coverage-text
