name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.6' # Version à adapter selon le projet
          extensions: mbstring, intl, bcmath, pdo, mysqli

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text